//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Train.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Road
    {
        public int From { get; set; }
        public int To { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int Id { get; set; }
        public int Distance { get; set; }
    
        public virtual City FromCity { get; set; }
        public virtual City ToCity { get; set; }
    }
}
